# Generated by Django 3.2.7 on 2021-10-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211005_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='No image', upload_to='articles/'),
        ),
    ]
